import React, { useEffect, useState } from 'react';
import { MessageSquare, Send } from 'lucide-react';
import { Case, CaseDocument, CaseNote } from '../types';
import { api } from '../api';

export const CaseNotesView: React.FC<{ currentCase: Case | null; documents: CaseDocument[] }> = ({ currentCase, documents }) => {
  const [notes, setNotes] = useState<CaseNote[]>([]);
  const [text, setText] = useState('');
  const [documentId, setDocumentId] = useState('');
  const [error, setError] = useState<string | null>(null);
  const load = async () => { if (currentCase) setNotes(await api.getCaseNotes(currentCase.case_id)); };
  useEffect(() => { load().catch((err) => setError(err.message)); }, [currentCase]);
  const add = async (event: React.FormEvent) => { event.preventDefault(); if (!currentCase || !text.trim()) return; try { await api.addCaseNote(currentCase.case_id, text, documentId); setText(''); await load(); } catch (err: any) { setError(err.message); } };
  if (!currentCase) return <div className="p-8 text-center text-xs text-[#5B5B5B]">Select a case to view its activity.</div>;
  return <div className="space-y-5"><div className="pb-3 border-b border-[#DDD9D1]"><h1 className="text-xl font-bold text-[#0A2540] flex items-center gap-2"><MessageSquare className="w-5 h-5 text-[#1F6F4A]" />Case Activity &amp; Notes</h1><p className="text-xs text-[#5B5B5B] mt-1">Shared plain-text notes for {currentCase.fir_number}. Every note is added to the audit ledger.</p></div><form onSubmit={add} className="bg-white border border-[#DDD9D1] rounded-[3px] p-4 space-y-3"><textarea value={text} onChange={(e) => setText(e.target.value)} maxLength={4000} placeholder="Add an operational note" className="w-full min-h-24 px-3 py-2 text-sm border border-[#DDD9D1] rounded-[3px]" /><div className="flex flex-col sm:flex-row gap-2"><select value={documentId} onChange={(e) => setDocumentId(e.target.value)} className="flex-1 px-3 py-2 text-xs border border-[#DDD9D1] rounded-[3px]"><option value="">Case-level note</option>{documents.map((doc) => <option key={doc.document_id} value={doc.document_id}>{doc.title}</option>)}</select><button disabled={!text.trim()} className="px-4 py-2 bg-[#0A2540] text-white text-xs font-semibold rounded-[3px] flex items-center justify-center gap-1.5 disabled:opacity-50"><Send className="w-3.5 h-3.5" />Add Note</button></div></form>{error && <div className="text-xs text-[#8C1D2B]">{error}</div>}<div className="bg-white border border-[#DDD9D1] rounded-[3px] divide-y divide-[#E9E6DF]">{notes.length === 0 ? <div className="p-8 text-center text-xs text-[#5B5B5B]">No notes recorded for this case.</div> : notes.map((note) => <article key={note.note_id} className="p-4"><div className="flex justify-between gap-3 text-[11px] text-[#5B5B5B]"><span className="font-semibold text-[#0A2540]">{note.author_name} · {note.author_role}</span><time>{new Date(note.created_at).toLocaleString()}</time></div><p className="text-sm mt-2 whitespace-pre-wrap">{note.note_text}</p></article>)}</div></div>;
};